"""Declarative data-cleaning rules for importable business tables."""

COMMON_ALIASES = {
    "store.name": ["store_name", "name", "shop_name", "门店名称", "店名", "门店", "门店名"],
    "store.city": ["city", "城市"],
    "store.address": ["address", "地址"],
    "store.area": ["area", "商圈", "区域"],
    "store.manager_name": ["manager", "manager_name", "店长", "负责人"],
    "store.seats": ["seats", "seat_count", "座位数"],
    "store.staff_count": ["staff", "staff_count", "员工数", "店员数"],
    "store.rating": ["rating", "评分"],
    "sku.store_id": ["store_id", "门店ID", "门店id"],
    "sku.date": ["date", "日期"],
    "sku.sku_name": ["sku_name", "product_name", "name", "商品名称", "商品名", "SKU名称"],
    "sku.category": ["category", "品类", "分类"],
    "sku.price": ["price", "unit_price", "单价", "售价"],
    "sku.cost": ["cost", "成本"],
    "sku.sales_count": ["sales", "sales_count", "销量", "销售量"],
    "sku.revenue": ["revenue", "sales_revenue", "营收", "销售额"],
    "sku.gross_margin": ["margin", "gross_margin", "毛利率"],
    "sku.refund_rate": ["refund_rate", "退单率", "退款率"],
    "metrics.date": ["date", "日期"],
    "metrics.store_id": ["store_id", "门店ID", "门店id"],
    "metrics.revenue": ["revenue", "total_revenue", "营收", "销售额"],
    "metrics.order_count": ["orders", "order_count", "订单数"],
    "metrics.avg_ticket": ["avg_ticket", "avg_order_value", "客单价"],
    "metrics.gross_margin": ["margin", "gross_margin", "毛利率"],
    "metrics.refund_rate": ["refund_rate", "退单率", "退款率"],
    "metrics.platform_commission": ["commission", "platform_commission", "平台抽佣"],
    "metrics.net_profit": ["profit", "net_profit", "净利润"],
    "metrics.delivery_ratio": ["delivery_ratio", "外卖占比"],
    "metrics.dine_in_ratio": ["dine_in_ratio", "堂食占比"],
    "metrics.new_customers": ["new_customers", "新客数"],
    "metrics.returning_customers": ["returning_customers", "回头客"],
    "campaign.campaign_name": ["campaign_name", "name", "活动名称", "活动名"],
    "campaign.channel": ["channel", "渠道"],
    "campaign.budget": ["budget", "预算"],
    "campaign.target_audience": ["target_audience", "目标受众"],
    "campaign.content_text": ["content", "content_text", "文案"],
    "staff.store_id": ["store_id", "门店ID", "门店id"],
    "staff.name": ["name", "staff_name", "姓名", "店员姓名"],
    "staff.phone": ["phone", "mobile", "手机号", "手机"],
    "staff.role": ["role", "岗位", "角色"],
    "staff.email": ["email", "邮箱"],
    "staff.id_number": ["id_number", "身份证号"],
    "staff.hire_date": ["hire_date", "入职日期"],
    "staff.status": ["status", "状态"],
    "staff.salary": ["salary", "薪资", "工资"],
    "staff.notes": ["notes", "备注"],
}


TABLE_RULES = {
    "store": {
        "required": ["store.name"],
        "dedupe_key": ["store.name"],
        "defaults": {"store.city": "", "store.address": "", "store.area": "", "store.rating": 4.5},
        "types": {
            "store.name": "str",
            "store.city": "str",
            "store.address": "str",
            "store.area": "str",
            "store.manager_name": "str",
            "store.seats": "int",
            "store.staff_count": "int",
            "store.rating": "float",
        },
        "ranges": {
            "store.seats": {"min": 0},
            "store.staff_count": {"min": 0},
            "store.rating": {"min": 0, "max": 5},
        },
    },
    "sku": {
        "required": ["sku.sku_name"],
        "dedupe_key": ["sku.store_id", "sku.date", "sku.sku_name"],
        "defaults": {"sku.store_id": 1, "sku.category": "未分类"},
        "types": {
            "sku.store_id": "int",
            "sku.date": "date",
            "sku.sku_name": "str",
            "sku.category": "str",
            "sku.price": "money",
            "sku.cost": "money",
            "sku.sales_count": "int",
            "sku.revenue": "money",
            "sku.gross_margin": "percent",
            "sku.refund_rate": "percent",
        },
        "ranges": {
            "sku.store_id": {"min": 1},
            "sku.price": {"min": 0},
            "sku.cost": {"min": 0},
            "sku.sales_count": {"min": 0},
            "sku.revenue": {"min": 0},
            "sku.gross_margin": {"min": -1, "max": 1},
            "sku.refund_rate": {"min": 0, "max": 1},
        },
    },
    "metrics": {
        "required": ["metrics.date"],
        "dedupe_key": ["metrics.store_id", "metrics.date"],
        "defaults": {"metrics.store_id": 1},
        "types": {
            "metrics.store_id": "int",
            "metrics.date": "date",
            "metrics.revenue": "money",
            "metrics.order_count": "int",
            "metrics.avg_ticket": "money",
            "metrics.gross_margin": "percent",
            "metrics.refund_rate": "percent",
            "metrics.platform_commission": "money",
            "metrics.net_profit": "money",
            "metrics.delivery_ratio": "percent",
            "metrics.dine_in_ratio": "percent",
            "metrics.new_customers": "int",
            "metrics.returning_customers": "int",
        },
        "ranges": {
            "metrics.store_id": {"min": 1},
            "metrics.revenue": {"min": 0},
            "metrics.order_count": {"min": 0},
            "metrics.avg_ticket": {"min": 0},
            "metrics.gross_margin": {"min": -1, "max": 1},
            "metrics.refund_rate": {"min": 0, "max": 1},
            "metrics.delivery_ratio": {"min": 0, "max": 1},
            "metrics.dine_in_ratio": {"min": 0, "max": 1},
            "metrics.new_customers": {"min": 0},
            "metrics.returning_customers": {"min": 0},
        },
    },
    "campaign": {
        "required": ["campaign.campaign_name"],
        "dedupe_key": ["campaign.campaign_name"],
        "defaults": {"campaign.channel": "全渠道"},
        "types": {
            "campaign.campaign_name": "str",
            "campaign.channel": "str",
            "campaign.budget": "money",
            "campaign.target_audience": "str",
            "campaign.content_text": "str",
        },
        "ranges": {"campaign.budget": {"min": 0}},
    },
    "staff": {
        "required": ["staff.name"],
        "dedupe_key": ["staff.store_id", "staff.name"],
        "defaults": {"staff.store_id": 1, "staff.role": "staff", "staff.status": "active"},
        "types": {
            "staff.store_id": "int",
            "staff.name": "str",
            "staff.phone": "str",
            "staff.role": "str",
            "staff.email": "str",
            "staff.id_number": "str",
            "staff.hire_date": "date",
            "staff.status": "str",
            "staff.salary": "money",
            "staff.notes": "str",
        },
        "ranges": {"staff.store_id": {"min": 1}, "staff.salary": {"min": 0}},
    },
}


TARGET_ALIASES = {
    "stores": "store",
    "store": "store",
    "products": "sku",
    "product": "sku",
    "sku": "sku",
    "metrics": "metrics",
    "metric": "metrics",
    "campaigns": "campaign",
    "campaign": "campaign",
    "marketing": "campaign",
    "staff": "staff",
}
