"""initial_schema

Revision ID: 907656cdedac
Revises: 
Create Date: 2026-06-08 19:51:29.466850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '907656cdedac'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sku_performance', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.add_column('sku_performance', sa.Column('price', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sku_performance', 'price')
    op.drop_column('sku_performance', 'image_url')
    # ### end Alembic commands ###
